version: 2

sources:
  - name: medallion_db
    database: medallion_db
    schema: bronze
    tables:
      - name: raw_customers
      - name: raw_products
      - name: raw_orders
      - name: raw_payments
      - name: raw_inventory
      - name: raw_shipments
      - name: raw_returns
      - name: raw_marketing
